### ISSUE TITLE
needs more commands

### ISSUE THREAD

**Issue by Ccode-lang** [Ccode-lang/echo-lang#1]
This repo needs more commands.  The code is simple and it should be easy to implement new commands. Good luck and happy hacktoberfest!

**Comment by StreakSharn** [comment]
What sort of commands fit the project? As far as I can see, so far it's mostly just about outputting text - do you mean adding things like maths operators?

**Comment by Ccode-lang** [comment]
Yes, that if possible.  

Also it is a shell so maybe things like 'ls' or 'cd'.

**Comment by Ccode-lang** [comment]
Hacktoberfest is over now so closing this.
